// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_rzFW6qty6JpoWsLvb8v7jn0fu53-CeQ',
    appId: '1:299643360887:web:ffe4979983cbaa9ffb9872',
    messagingSenderId: '299643360887',
    projectId: 'mytask-71af9',
    authDomain: 'mytask-71af9.firebaseapp.com',
    storageBucket: 'mytask-71af9.appspot.com',
    measurementId: 'G-9RB1F38V5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHRjt45au01YktAldlfUDU_5c4C5jjLTs',
    appId: '1:299643360887:android:51e1016ea3ccb1fefb9872',
    messagingSenderId: '299643360887',
    projectId: 'mytask-71af9',
    storageBucket: 'mytask-71af9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOxOYX-vdxty_AlX6ewsIxqqeexz-i3wQ',
    appId: '1:299643360887:ios:6df15ed46b2f6494fb9872',
    messagingSenderId: '299643360887',
    projectId: 'mytask-71af9',
    storageBucket: 'mytask-71af9.appspot.com',
    iosClientId: '299643360887-7om2trgk4dmbg5d7sgi9opugehg4rn9a.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );
}
